# Generated by Django 2.2.1 on 2019-06-04 08:22

from django.db import migrations, models
import django.db.models.deletion
import onlinestore.models
import onlinestore.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(onlinestore.utils.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.FileField(upload_to='static/images', validators=[onlinestore.models.validate_file_extension])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.Category')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(onlinestore.utils.SlugMixin, models.Model),
        ),
    ]
